version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
  - dependency-name: System.Drawing.Common
    versions:
    - 5.0.0
    - 5.0.1
